#!/usr/bin/env python3
# Copyright 2026 Outdoor Patrol Team
# Licensed under the Apache License, Version 2.0.
"""Console entry point for the indoor rehearsal stack."""

from outdoor_patrol_validation.field_rehearsal_node import main

if __name__ == '__main__':
    main()
